name: Deploy VitePress Docs

env:
  DEPLOY_HOST_IP: "52.37.45.2"
  PATH_TO_DEPLOY: "/mnt/deploy/www"

on:
  workflow_dispatch:
  push:
    paths-ignore: [".github/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set UTF-8 Encoding
        run: echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      - name: Checkout application code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build docs
        run: npm run docs:build

      - name: Achieve artifacts
        run: |
          cd docs/.vitepress/
          tar cvf dist.tar -C dist .
          ls -lh dist.tar

      - name: Add ssh key
        run: |
          mkdir -p $HOME/.ssh/
          echo "${{ secrets.DEPLOY_SSH }}" | base64 -d  > $HOME/.ssh/id_rsa_deploy
          ls -lh $HOME/.ssh/id_rsa_deploy
          chmod 600 $HOME/.ssh/id_rsa_deploy

      - name: Upload archive
        run: |
          scp -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa_deploy "$GITHUB_WORKSPACE/docs/.vitepress/dist.tar" root@$DEPLOY_HOST_IP:$PATH_TO_DEPLOY/

  #    - name: Deploy archive
  #      run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa_deploy root@$DEPLOY_HOST_IP "cd $PATH_TO_DEPLOY && tar xvf $PATH_TO_DEPLOY/dist.tar"

  #    - name: Remove archive
  #      run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa_deploy root@$DEPLOY_HOST_IP "rm -f $PATH_TO_DEPLOY/dist.tar"

      - name: Remove ssh key
        if: always()
        run: rm -f $HOME/.ssh/id_rsa_deploy || true
